import "./globals.css";
import Navbar from "./ui/navbar/Navbar";

export const metadata = {
  title: "Yugto",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="flex flex-col h-full w-full">
          <Navbar />
          <div className="flex-1 h-10 bg-red-100">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
